# Generated by Django 3.2.25 on 2025-05-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('cultural', 'Cultural'), ('music', 'Music'), ('food', 'Food & Drink'), ('sports', 'Sports'), ('business', 'Business'), ('educational', 'Educational'), ('religious', 'Religious'), ('festival', 'Festival'), ('historical', 'Historical'), ('other', 'Other')], max_length=20),
        ),
    ]
