# Generated by Django 3.2.25 on 2025-04-29 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('duration_in_days', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=200)),
                ('gallery_images', models.JSONField(default=list)),
                ('category', models.JSONField(default=list)),
                ('included', models.JSONField(default=list)),
                ('not_included', models.JSONField(default=list)),
                ('itinerary', models.JSONField(default=list)),
                ('departure', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('max_group_size', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Challenging', 'Challenging')], max_length=20)),
                ('tour_guide', models.CharField(max_length=100)),
                ('languages', models.JSONField(default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('coordinates', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='packages.package')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packages.package')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('available_slots', models.IntegerField(null=True)),
                ('is_guaranteed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='packages.package')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='savedpackage',
            index=models.Index(fields=['user'], name='packages_sa_user_id_1f87d2_idx'),
        ),
        migrations.AddIndex(
            model_name='savedpackage',
            index=models.Index(fields=['package'], name='packages_sa_package_6d168f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedpackage',
            unique_together={('user', 'package')},
        ),
        migrations.AddIndex(
            model_name='packagereview',
            index=models.Index(fields=['package'], name='packages_pa_package_b5271d_idx'),
        ),
        migrations.AddIndex(
            model_name='packagereview',
            index=models.Index(fields=['user'], name='packages_pa_user_id_66aa0d_idx'),
        ),
        migrations.AddIndex(
            model_name='packagereview',
            index=models.Index(fields=['rating'], name='packages_pa_rating_c9f54e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='packagereview',
            unique_together={('package', 'user')},
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['slug'], name='packages_pa_slug_a25c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['category'], name='packages_pa_categor_ffec45_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['region'], name='packages_pa_region_56b8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['featured'], name='packages_pa_feature_4c4273_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status'], name='packages_pa_status_1e0453_idx'),
        ),
        migrations.AddIndex(
            model_name='departure',
            index=models.Index(fields=['start_date'], name='packages_de_start_d_6cabb0_idx'),
        ),
        migrations.AddIndex(
            model_name='departure',
            index=models.Index(fields=['is_guaranteed'], name='packages_de_is_guar_8f4213_idx'),
        ),
    ]
