# Generated by Django 3.2.25 on 2025-05-14 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import packages.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='package',
            name='packages_pa_categor_ffec45_idx',
        ),
        migrations.RemoveField(
            model_name='package',
            name='user',
        ),
        migrations.AddField(
            model_name='package',
            name='organizer',
            field=models.ForeignKey(default='967315d1-ead0-4cdf-b4f2-9b5945a5ccf2', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departure',
            name='available_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='departure',
            name='end_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='packages.package'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='departure',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.JSONField(default=packages.models.default_json_list),
        ),
        migrations.AlterField(
            model_name='package',
            name='coordinates',
            field=models.JSONField(default=packages.models.default_json_list),
        ),
        migrations.AlterField(
            model_name='package',
            name='gallery_images',
            field=models.JSONField(default=packages.models.default_json_list),
        ),
        migrations.AlterField(
            model_name='package',
            name='included',
            field=models.JSONField(default=packages.models.default_json_list),
        ),
        migrations.AlterField(
            model_name='package',
            name='itinerary',
            field=models.JSONField(default=packages.models.default_json_list),
        ),
        migrations.AlterField(
            model_name='package',
            name='languages',
            field=models.JSONField(default=packages.models.default_json_list),
        ),
        migrations.AlterField(
            model_name='package',
            name='not_included',
            field=models.JSONField(default=packages.models.default_json_list),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packages.package'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='user',
            field=models.ForeignKey(default='967315d1-ead0-4cdf-b4f2-9b5945a5ccf2', on_delete=django.db.models.deletion.CASCADE, related_name='package_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedpackage',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='packages.package'),
        ),
        migrations.AlterField(
            model_name='savedpackage',
            name='user',
            field=models.ForeignKey(default='967315d1-ead0-4cdf-b4f2-9b5945a5ccf2', on_delete=django.db.models.deletion.CASCADE, related_name='saved_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
