# Generated by Django 3.2.25 on 2025-05-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20250515_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagereview',
            name='helpful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagereview',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='packagereview',
            index=models.Index(fields=['helpful'], name='packages_pa_helpful_3c9e22_idx'),
        ),
        migrations.AddIndex(
            model_name='packagereview',
            index=models.Index(fields=['reported'], name='packages_pa_reporte_08c230_idx'),
        ),
    ]
