# Generated by Django 3.2.25 on 2025-05-24 09:59

from django.db import migrations, models
import packages.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20250515_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='coordinates',
            field=models.JSONField(blank=True, default=packages.models.default_json_list, null=True),
        ),
    ]
