# Generated by Django 3.2.25 on 2025-04-29 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('historical', 'Historical'), ('natural', 'Natural'), ('cultural', 'Cultural'), ('religious', 'Religious'), ('adventure', 'Adventure'), ('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City')], max_length=20)),
                ('region', models.CharField(choices=[('addis_ababa', 'Addis Ababa'), ('afar', 'Afar'), ('amhara', 'Amhara'), ('benishangul_gumuz', 'Benishangul-Gumuz'), ('diredawa', 'Dire Dawa'), ('gambela', 'Gambela'), ('harari', 'Harari'), ('oromia', 'Oromia'), ('sidama', 'Sidama'), ('somali', 'Somali'), ('south_west', 'South West'), ('southern', 'Southern'), ('tigray', 'Tigray')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('images', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='destinations.destination')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_destinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('helpful', models.IntegerField(default=0)),
                ('reported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.destination')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='saveddestination',
            index=models.Index(fields=['user'], name='destination_user_id_d02067_idx'),
        ),
        migrations.AddIndex(
            model_name='saveddestination',
            index=models.Index(fields=['destination'], name='destination_destina_aa0d82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saveddestination',
            unique_together={('user', 'destination')},
        ),
        migrations.AddIndex(
            model_name='destinationreview',
            index=models.Index(fields=['destination'], name='destination_destina_4a0a56_idx'),
        ),
        migrations.AddIndex(
            model_name='destinationreview',
            index=models.Index(fields=['user'], name='destination_user_id_27bd50_idx'),
        ),
        migrations.AddIndex(
            model_name='destinationreview',
            index=models.Index(fields=['rating'], name='destination_rating_19515c_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['slug'], name='destination_slug_528bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['category'], name='destination_categor_7c9900_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['region'], name='destination_region_ebb36c_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['featured'], name='destination_feature_05c406_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['status'], name='destination_status_39abee_idx'),
        ),
    ]
