# Generated by Django 3.2.25 on 2025-04-29 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('events', '0001_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('number_of_people', models.IntegerField(default=1)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('chapa', 'Chapa'), ('cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_details', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('helpful', models.IntegerField(default=0)),
                ('reported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.booking')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking'], name='booking_pay_booking_958219_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='booking_pay_status_cb1e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='booking_pay_payment_e46319_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingreview',
            index=models.Index(fields=['booking'], name='booking_boo_booking_64c812_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingreview',
            index=models.Index(fields=['rating'], name='booking_boo_rating_3e9ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='booking_boo_user_id_d9826d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event'], name='booking_boo_event_i_fc03c0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['business'], name='booking_boo_busines_de0a93_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['package'], name='booking_boo_package_137090_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_boo_status_e01616_idx'),
        ),
    ]
