# Generated by Django 3.2.25 on 2025-04-29 19:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('business_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('main_image', models.URLField(max_length=500)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('social_media_links', models.JSONField(blank=True, default=dict)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=list)),
                ('team', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='SavedBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('is_reported', models.BooleanField(default=False)),
                ('report_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='savedbusiness',
            index=models.Index(fields=['user', 'business'], name='business_sa_user_id_883a07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedbusiness',
            unique_together={('user', 'business')},
        ),
        migrations.AddIndex(
            model_name='businessreview',
            index=models.Index(fields=['business', 'user'], name='business_bu_busines_925b02_idx'),
        ),
        migrations.AddIndex(
            model_name='businessreview',
            index=models.Index(fields=['rating'], name='business_bu_rating_81c06a_idx'),
        ),
        migrations.AddIndex(
            model_name='businessreview',
            index=models.Index(fields=['is_reported'], name='business_bu_is_repo_6a820d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessreview',
            unique_together={('business', 'user')},
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['name'], name='business_bu_name_217b62_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_type'], name='business_bu_busines_c2daf2_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['region'], name='business_bu_region_0ae2db_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['city'], name='business_bu_city_20b1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status'], name='business_bu_status_db4803_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_featured'], name='business_bu_is_feat_41d1d6_idx'),
        ),
    ]
