# Generated by Django 3.2.25 on 2025-05-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_verified'], name='business_bu_is_veri_793c55_idx'),
        ),
    ]
